### ISSUE TITLE
Custom Post Layouts Don't Work At All

### ISSUE THREAD

**Issue by NitroShellMKDS** [rollerozxa/ABXD#2]

**Comment by rollerozxa** [comment]
I'm unsure as to what the cause of that would be, whether it's caused by my changes or by ABXD upstream. Either way, I don't really support for this fork. ABXD is an ancient mess, you're better off finding more maintained forks of it than this one.

**Comment by ghost** [comment]
It seems to be caused by whatever hodgepodge of changes are present on Landon's board, which seems to be a mashup of changes from here and MoonlightCapital's old fork from April 2017.

Which I can attest, from having personally worked on it back in the day, is a complete shitshow.

**Comment by rollerozxa** [comment]
> It seems to be caused by whatever hodgepodge of changes are present on Landon's board, which seems to be a mashup of changes from here and MoonlightCapital's old fork from April 2017.

Oh geez. Good luck with that frankenboard codebase I guess.
